version: "3.1"
services:
  php:
    build: "./drupal"
    hostname: "php"
    environment:
      - DRUPAL_ENV
    logging:
      options:
        max-size: 128m
    volumes:
      - "./../src:/var/www/html"
      - "./../data:/data"
    ports:
      - "10001:80"
  mysql:
    build: "./mysql"
    hostname: "mysql"
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: Password1
      MYSQL_ROOT_PASSWORD: Password1
    ports:
      - "10002:3306"
    restart: on-failure
    logging:
      options:
        max-size: 128m
    volumes:
      - "./../data/mysql:/var/lib/mysql"
      - "./../data:/data"
